---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno"
  namespace: "ztp-site"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    sites: "sno"
  mcp: "master"
  sourceFiles:
    - fileName: SriovNetwork.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nw-sno005"
      spec:
        resourceName: sno005
        vlan: 301
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-sno005"
      spec:
        deviceType: vfio-pci
        isRdma: false
        nicSelector:
          pfNames: ["eno50"]
        numVfs: 8
        priority: 10
        resourceName: nic1
    - fileName: SriovNetwork.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nw-sno007"
      spec:
        resourceName: sno007
        vlan: 301
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-sno007"
      spec:
        deviceType: vfio-pci
        isRdma: false
        nicSelector:
          pfNames: ["eno50"]
        numVfs: 8
        priority: 10
        resourceName: nic1
   
    
