apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno168"
  namespace: "sno168"
spec:
  baseDomain: "workload.bos2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-sno168"
  clusterImageSetNameRef: "img4.14.5-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAxsCxf5WyyqrHRysq3hJaNibAN91YaciKfF2BCb6PDV kni@ocp414-prov"
  clusters:
  - clusterName: sno168
    networkType: OVNKubernetes
    clusterLabels:
      ocp-version: "4.14"
      common: "true"
      group-du-sno: "core"
      sites: bos2
    extraManifests:
    #searchPaths:
      #- extra-manifest/
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.18.0/25
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - pool.ntp.org
    extraManifests:
      filter:
        inclusionDefault: include
    cpuPartitioningMode: None
    clusterProfile: du
    clusterType: sno    
    nodes:
    - hostName: sno168.workload.bos2.lab
      role: "master"
      bmcAddress: "idrac-virtualmedia://192.168.18.168/redfish/v1/Systems/System.Embedded.1"
      installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
      bmcCredentialsName:
        name: sno168-bmc-secret
      bootMACAddress: B4:83:51:0A:39:20
      bootMode: UEFI
      rootDeviceHints:
        deviceName: /dev/nvme0n1
      #cpuset: "0-1,30-33,62-63"      
      nodeNetwork:
          interfaces:
            - name: "ens2f0"
              macAddress: "B4:83:51:0A:39:20"
          config:
            interfaces:
              - name: "ens2f0"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.18.50
                    prefix-length: 25
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                - workload.bos2.lab 
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens2f0
                next-hop-address: 192.168.18.1
                table-id: 254