apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "bos2"
  namespace: "ztp-site-core"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    sites: "bos2"
    du-profile: "4.14"
  mcp: "master"
  sourceFiles:
    - fileName: SriovNetwork.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nw-sno168"
        namespace: openshift-sriov-network-operator
      spec:
        resourceName: sno168
        networkNamespace: openshift-sriov-network-operator
        vlan: 168
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-sno168"
        namespace: openshift-sriov-network-operator
      spec:
        resourceName: sno168
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 10
        mtu: 1800
        numVfs: 8
        nicSelector:
          pfNames: ["ens2f0"]
        deviceType: vfio-pci
        isRdma: false
    - fileName: SriovNetwork.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nw-sno170"
        namespace: openshift-sriov-network-operator
      spec:
        resourceName: sno170
        networkNamespace: openshift-sriov-network-operator
        vlan: 168
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-sno170"
        namespace: openshift-sriov-network-operator
      spec:
        resourceName: sno170
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 10
        mtu: 1800
        numVfs: 8
        nicSelector:
          pfNames: ["ens2f0"]
        deviceType: vfio-pci
        isRdma: false        