apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno007"
  namespace: "sno007"
  labels:
    forcesync: "2"
spec:
  baseDomain: "hpecloud.rdu2.eng.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-sno007"
  clusterImageSetNameRef: "img4.10.45-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtSAUavTTr4dTvMOqZ/A6mg9q++qrVSNIu3vICnGUPpKGmQk4227TlaL9iwBkBqbGMvOaBZwn/b3URk/QE/El5ElzqaNNJxHqxWHGNKOJB49sVj5f57Usw07WyMy8CDy0Hk701jzvrdxqckfMEmMzWjE0C7Zpus6J3GyG3ANTYbSQGRtzdz7bcg05Xm0xCzfC/HAEF6Arz/cTv9k9rioiu1reV1qqq+FAlnKx3x/+XsG5cHMhnVuUnOU59p9pOh+v/nxq5Ysz/5iJrKNmJqkUAPShrfs3Kk2Z8TJVoEKoyyfme4uNAqBg2xZjnaPf8avfmc8uYzjHN7BA4w1fMw/mO71FCXkuxukttUeoqO2ARpofwzIeiH2wmJ7fKLaomETbZyIzYiVoZM2VKu1nPNmWOluqrpvNBnufWLpmRqWntmvT26IEGmlAjTz1HV0VZXVo+6viI3RQTJJXeZ7uTjCPz/uVsrv5U2BthWIkJ7OJEB0mcwbSJF5FOhML8dZ+/ODc= mjanardh@mjanardh.remote.csb"
  clusters:
  - additionalNTPSources:
    - pool.ntp.org
    - clock.corp.redhat.com
    - 10.2.32.38
    - 10.2.32.37
    - 10.11.160.238
    clusterLabels:
      common: true
      group-du-sno: ""
      sites: sno
    clusterName: sno007
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    clusterProfile: du
    clusterType: sno
    machineNetwork:
      - cidr: 10.6.30.0/24
    serviceNetwork:
      - 172.30.0.0/16
    networkType: OVNKubernetes
    nodes:
    - bmcAddress: ipmi://10.6.33.7
      bmcCredentialsName:
        name: sno007-bmc-secret
      bootMACAddress: 14:02:ec:93:d8:b1
      bootMode: UEFI
      rootDeviceHints:
        deviceName: /dev/sdb
      cpuset: "0-1,30-33,62-63"
      hostName: sno007.hpecloud.rdu2.eng.redhat.com
      nodeNetwork:
          interfaces:
            - name: "eno50"
              macAddress: "14:02:ec:93:d8:b1"
          config:
            interfaces:
              - name: "eno50"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  - ip: 10.6.30.27
                    prefix-length: 24
            dns-resolver:
              config:
                search:
                - hpecloud.rdu2.eng.redhat.com 
                server:
                - 10.6.30.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: eno50
                next-hop-address: 10.6.30.254
                table-id: 254